version: '3.7'
services:

  mysql-querydsl-cookbook:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-querydsl-cookbook
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "mike"
      MYSQL_PASSWORD: "mike-password"
