CREATE TABLE DEPARTMENT
(
    ID   NUMBER PRIMARY KEY AUTO_INCREMENT,
    CODE NUMBER UNIQUE NOT NULL,
    NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE EMPLOYEE
(
    ID              NUMBER PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME      VARCHAR2(50),
    LAST_NAME       VARCHAR2(50),
    SALARY          NUMBER,
    DEPARTMENT_CODE NUMBER NOT NULL,
    FOREIGN KEY (DEPARTMENT_CODE) REFERENCES DEPARTMENT (CODE)
);

